//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenKey.rc
//
#define IDI_APP_ICON                    1
#define IDC_MYICON                      2
#define IDOK2                           2
#define IDBUTTON_OK                     2
#define IDOK3                           3
#define IDBUTTON_EXIT                   3
#define IDD_OPENKEY_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_TRAY_TITLE                  104
#define IDM_EXIT                        105
#define IDS_TRAY_TITLE_2                105
#define IDS_STRING_CONVERT_COMPLETED    106
#define IDS_MAIN_DIALOG_TITLE           107
#define IDC_OPENKEY                     109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAIN                 129
#define IDI_ICON1                       133
#define IDI_ICON_STATUS_VIET            134
#define IDI_ICON2                       135
#define IDI_ICON_STATUS_ENGLISH         135
#define IDI_ICON_STATUS_ENG             135
#define IDI_ICON_STATUS_VIET_10         136
#define IDI_ICON4                       137
#define IDI_ICON_STATUS_ENG_10          137
#define IDI_ICON_OK_BUTTON              138
#define IDI_ICON_EXIT_BUTTON            139
#define IDI_ICON3                       140
#define IDI_ICON_DEFAULT_BUTTON         140
#define IDD_DIALOG_MACRO                141
#define IDD_DIALOG_CONVERT_TOOL         142
#define IDI_ICON5                       143
#define IDI_ICON_START_CONVERT          143
#define IDC_COMBO1                      1000
#define IDC_COMBO_INPUT_TYPE            1000
#define IDC_CHECK1                      1001
#define IDC_CHECK_SWITCH_KEY_CTRL       1001
#define IDC_COMBO2                      1002
#define IDC_COMBO_TABLE_CODE            1002
#define IDC_CHECK2                      1003
#define IDC_CHECK_SWITCH_KEY_ALT        1003
#define IDC_CHECK3                      1004
#define IDC_CHECK_SWITCH_KEY_WIN        1004
#define IDC_CHECK4                      1005
#define IDC_CHECK_SWITCH_KEY_SHIFT      1005
#define IDC_EDIT1                       1006
#define IDC_SWITCH_KEY_KEY              1006
#define IDC_EDIT_MACRO_NAME             1006
#define IDC_CHECK5                      1007
#define IDC_CHECK_SWITCH_KEY_BEEP       1007
#define IDC_COMBO_TABLE_CODE_DST        1007
#define IDC_RADIO1                      1008
#define IDC_RADIO_METHOD_VIETNAMESE     1008
#define IDC_RADIO2                      1009
#define IDC_RADIO_METHOD_ENGLISH        1009
#define IDC_CHECK6                      1010
#define IDC_CHECK_MODERN_ORTHORGRAPHY   1010
#define IDC_CHECK7                      1011
#define IDC_CHECK_SPELLING              1011
#define IDC_CHECK_REMOVE_MARK           1011
#define IDC_CHECK8                      1012
#define IDC_CHECK_RESTORE_IF_WRONG_SPELLING 1012
#define IDC_CHECK_NON_ALL_CAPS          1012
#define IDC_CHECK9                      1013
#define IDC_CHECK_FIX_RECOMMEND_BROWSER 1013
#define IDC_CHECK_CAPS_FIRSTWORD        1013
#define IDC_CHECK_CAPS_FIRST_LETTER     1013
#define IDC_CHECK10                     1014
#define IDC_CHECK_SHOW_ON_STARTUP       1014
#define IDC_CHECK_FIRST_LETTER          1014
#define IDC_CHECK_EACH_WORD             1014
#define IDC_CHECK11                     1015
#define IDC_CHECK_RUN_WITH_WINDOWS      1015
#define IDC_CHECK_ALERT_WHEN_COMPLETED  1015
#define IDC_CHECK12                     1016
#define IDC_CHECK_USE_CLIPBOARD         1016
#define IDC_CHECK_CONVERT_CLIPBOARD     1016
#define IDC_CHECK13                     1017
#define IDC_CHECK_SMART_SWITCH_KEY      1017
#define IDC_CHECK14                     1018
#define IDC_CHECK_CAPS_FIRST_CHAR       1018
#define IDC_CHECK15                     1019
#define IDC_CHECK_QUICK_TELEX           1019
#define IDC_CHECK16                     1020
#define IDC_CHECK_USE_MACRO             1020
#define IDC_CHECK17                     1021
#define IDC_CHECK_USE_MACRO_IN_ENGLISH  1021
#define IDC_BUTTON1                     1022
#define IDC_BUTTON_MACRO_TABLE          1022
#define IDC_BUTTON_CHECK_VERSION        1022
#define IDC_BUTTON_CONVERT_BUTTON       1022
#define IDC_BUTTON_ADD                  1022
#define ID_BTN_DEFAULT                  1023
#define IDC_CHECK_MODERN_ICON           1024
#define IDC_STATIC_APP_TITLE            1024
#define IDC_STATIC_APP_SUB_TITLE        1025
#define IDC_CHECK_TEMP_OFF_SPELLING     1025
#define IDC_STATIC_APP_VERSION          1026
#define IDC_CHECK_ALLOW_ZJWF            1026
#define IDC_SYSLINK_HOME_PAGE           1027
#define IDC_CHECK_QUICK_START_CONSONANT 1027
#define IDC_STATIC_APP_SUB_TITLE2       1028
#define IDC_CHECK_QUICK_END_CONSONANT   1028
#define IDC_STATIC_APP_SUB_TITLE3       1029
#define IDC_STATIC_APP_SUB_TITLE4       1030
#define IDC_SYSLINK_NEW_VERSION         1031
#define IDC_SYSLINK_FANPAGE             1032
#define IDC_STATIC_APP_SUB_TITLE5       1033
#define IDC_SPLIT1                      1035
#define IDC_LIST3                       1038
#define IDC_LIST_MACRO_DATA             1038
#define IDC_BUTTON_CONVERT_SWITCH       1039
#define IDC_CHECK_All_CAPS              1040
#define IDC_COMBO_TABLE_CODE_SRC        1041
#define IDC_EDIT_MACRO_CONTENT          1042
#define IDC_BUTTON_DELETE               1043
#define IDC_BUTTON_IMPORT_MACRO         1044
#define IDC_BUTTON3                     1045
#define IDC_BUTTON_EXPORT_MACRO         1045
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
